### ISSUE TITLE
Shift+H + DynamicMacros don't mix well

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope#1171]
While trying to test Chrysalis' macro editor, I ran into an issue where I set up a macro as `TapSequence Shift+h e l l o SPACE w o r l d Shift+1`, and only "eh" comes out of it.

Not using `Shift +` makes the macro come out well.

I have not debugged it further. There's a chance that DynamicMacros bitrotted, and doesn't do things the same way Macros does anymore. I also need to test the same sequence with Macros, to be sure, too.

**Comment by algernon** [comment]
Further testing shows that `KeyDown Shift, Tap H, KeyUp Shift` doesn't work either, only `h` comes out. I haven't checked the reports yet, to see if ever do anything with shift.

**Comment by gedankenexperimenter** [comment]
I'm not sure, but I see something that might be the problem, or part of it.  DynamicMacros is missing the `beforeReportingState()` handler that Macros uses to add keys in its supplemental array to the report.  I'm pretty sure this explains the second problem (where the pressed `shift` gets dropped), but not the first one.

**Comment by gedankenexperimenter** [comment]
For both Macros and DynamicMacros, `MACRO_ACTION_STEP_TAP_SEQUENCE` looks wrong to me.  It doesn't read whole `Key` objects, but instead just reads one byte at a time and treats that as a keycode.  So with the first two characters of the sequence being `shift`+`h`, then `e`, the `shift` becomes `0x08`, which happens to be `e`, and the `h` is just an `h`.  The next byte is `0` (the flags byte for the `e` of `Hello`), and that triggers the end of the sequence because it's treated as a keycode with a flags byte of `0`, which is `Key_NoKey`, which ends the sequence.  Thus the output becomes `eh`.  I'll have a PR with both fixes shortly.

**Comment by algernon** [comment]
Thank you for the quick look, the explanation, and the fix, very, very much appreciated!
