### ISSUE TITLE
(Re)defining a ShiftToLayer(N) key on layer N causes that layer to not turn off

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope#246]
If a key is defined on the base layer as `ShiftToLayer(N)`, and that same key is defined as something else on layer `N`, pressing and releasing that key will turn on layer `N`, but won't turn it off.

This happens because `updateLiveCompositeKeymap()` gets called on both key press and release events. It can be fixed by only updating on presses, instead. @algernon, @obra: Is there any reason that we need to update the keymap on release events?

**Comment by algernon** [comment]
The reason we want to update on release too, is because of the following scenario:

- Press and hold a `ShiftToLayer` key.
- Press and hold a key that is modified by the target layer, and can repeat.
- Wait.
- Release the `ShiftToLayer` key, but continue holding the other one.
- Wait.
- Release the other key too.

Lets suppose we held the `h`/`left arrow` key along with `Fn`. If we do not update the cache on release, the key will stay `left arrow` until pressed again. While that won't affect its behaviour much, it will affect any other code that does something based on the keymap, such as highlighting arrow keys, or anything similar.

**Comment by gedankenexperimenter** [comment]
> While that won't affect its behaviour much, it will affect any other code that does something based on the keymap, such as highlighting arrow keys, or anything similar.

What about keys that a plugin wants to hightlight, but which were never pressed? When do they get updated in the live keymap cache?

**Comment by gedankenexperimenter** [comment]
So, for example, I press and hold an `Fn` key, and then want the arrow keys highlighted. But those keys haven't toggled on _or_ off, so they're still `h`, `j`, `k`, and `l` in the `liveCompositeKeymap[]`, aren't they? Updating it on release as well as press doesn't provide the benefit you described. The only other place I can find `updateLiveCompositeKeymap()` being called is in `Kaleidoscop.setup()`.

**Comment by algernon** [comment]
> What about keys that a plugin wants to hightlight, but which were never pressed? When do they get updated in the live keymap cache?

The plugin can use the `lookupOnActiveLayer` there. On second thought, LED effects should probably use that to begin with.

So I went looking for other places where we use `Layer.lookup`, and only found a use in `DualUse` outside of Kaleidoscope core (and in `-LEDEffects`, but that should probably be using `lookupOnActiveLayer` instead).

Which means I no longer have a good argument against the change, it seems.
