### ISSUE TITLE
HID types in key_defs.h rendered useless by new `IS_CONSUMER` value

### ISSUE THREAD

**Issue by jamadagni** [keyboardio/Kaleidoscope#350]
Prior to https://github.com/keyboardio/Kaleidoscope/pull/242/commits/f57aab5f718d3b47ea2252ec6c006c96cc62eb59, the value of `IS_CONSUMER` was `B00000010` and this was OR-able with the values of the HID types:

```
#define HID_TYPE_CL    B00000000
#define HID_TYPE_LC    B00000100
#define HID_TYPE_NARY  B00001000
#define HID_TYPE_OOC   B00001100
#define HID_TYPE_OSC   B00010000
#define HID_TYPE_RTC   B00010100
#define HID_TYPE_SEL B00011000
```

In fact, the comment line https://github.com/keyboardio/Kaleidoscope/blob/master/src/key_defs.h#L100 still reads:
```
   We need to keep the bottom two bits clear for defining the keys as sysctl / consumerctl
```
… as if the value of `IS_CONSUMER` were still `B00000010`.

However, the value of `IS_CONSUMER` after above PR/commit became `B00001000` and this evidently conflicts with the above HID types as it uses a bit position used by them. That is, currently, after OR-ing, this renders the following pairs of values identical:

* `IS_CONSUMER | HID_TYPE_CL` and `IS_CONSUMER | HID_TYPE_NARY` are both `0b00001000`
* `IS_CONSUMER | HID_TYPE_LC` and `IS_CONSUMER | HID_TYPE_OOC` are both `0b00001100`
* `IS_CONSUMER | HID_TYPE_OSC` and `IS_CONSUMER | HID_TYPE_SEL` are both `0b00011000`

This has already been pointed out by @gedankenexperimenter in https://github.com/keyboardio/Kaleidoscope/pull/242#commitcomment-26441387 but apparently ignored. I'm quite surprised to say the least that such a PR was pulled without having the obvious conflict addressed.

Now it seems that either the HID type markers should be discarded, or their values modified to not conflict with the `IS_CONSUMER` value (and the `CONSUMER` and other stuff that that PR addressed)…

**Comment by gedankenexperimenter** [comment]
The low two bits need to be kept clear for Consumer Control keys not because that where the `IS_CONSUMER` bit was (erroneously) placed, but because Consumer Control keycodes are actually ten bits long. I don't recall well enough to be certain, but I think the `HID_TYPE_*` bits are superfluous; if you know the (ten bit) keycode, that should give you enough information to determine which HID type it is.

**Comment by algernon** [comment]
Since the `HID_TYPE_*` bits are never used in code, yet, consumer keys still work, I think these bits can be safely removed. They may be useful for the human reader, to see the HID types of a given key (for whatever reason), but then we could just set all of them to zero, and document that they're decoration only.

I would just remove them myself, because one can always consult the HID spec to figure out the types.. having them is not particularly useful in the firmware itself, I think.

@obra, what do you think?

**Comment by obra** [comment]
Closing. See #359 for further discussion.
