### ISSUE TITLE
HostPowerManagement: `toggleLedsOnSuspendResume` doesn't work

### ISSUE THREAD

**Issue by jamadagni** [keyboardio/Kaleidoscope#516]
Hello. Currently on https://github.com/keyboardio/Kaleidoscope-Bundle-Keyboardio/commit/fbe335e1ffd00ac0d587a23300cc7a891e2bc2ab which seems to be using 513e28d8cc4fba0e4c4c079b6d94f224924dcd57.

Using `toggleLedsOnSuspendResume` from [vanilla sketch](https://github.com/keyboardio/Model01-Firmware/blob/master/Model01-Firmware.ino) as part of [mine](https://gist.github.com/jamadagni/afe3848e1e5f95343e8e84fb6c60f4e7). 

The toggling doesn't work. That is, even if my computer (running Kubuntu Bionic with latest updates) goes to sleep, the LEDs don't go off. No change is seen on resume either.

However during host sleep the keyboard becomes unresponsive in the sense that LED mode changing or other keyboard-only operations don't work until the host is awoken.

Before the change to the monorepo it was working fine. That's all I know.

Please check and fix. Thanks.

**Comment by tiltowait** [comment]
I have the same issue—my LEDs won't turn off when my system (macOS 10.14) sleeps.

> However during host sleep the keyboard becomes unresponsive in the sense that LED mode changing or other keyboard-only operations don't work until the host is awoken.

I do not have this issue, however.

**Comment by algernon** [comment]
> However during host sleep the keyboard becomes unresponsive in the sense that LED mode changing or other keyboard-only operations don't work until the host is awoken.

Does this mean you are also unable to wake the host with the keyboard, and have to use another device?

**Comment by algernon** [comment]
Ok, I could reproduce the issue with LEDs not going off, it is caused by cac8e0f6149f17f9d9f40ba4bc85939706a9a6a4. The fix for that is to change your sketch to pause *after* `LEDControl.syncLeds()`. See keyboardio/Model01-Firmware#76.

LED mode changing not working while suspended is intentional, as we disable all kinds of LED updates during suspend, so that part is not a bug. If you want to turn LEDs off, but still allow LED mode changing, you can remove the `LEDControl.paused = true` line. Mind you, key presses will wake up the host, so you won't be able to play with LEDs while the host sleeps.

**Comment by jamadagni** [comment]
Moving `LEDControl.paused = true` fixed the problem. Thanks!
