### ISSUE TITLE
Escape key is broken when using OneShot and Escape-OneShot

### ISSUE THREAD

**Issue by TreTuna** [keyboardio/Kaleidoscope#572]
When using the current master in combination with OneShots and Escape-OneShot, the Escape key is broken and Escape-OneShot works, but it doesn't send the keycode out to the host.

After a `git bisect` it seems that the culprit was [OneShot: Switch from 16-bit bitfields to using a struct](https://github.com/keyboardio/Kaleidoscope/commit/032da484bc8b55e9df450e394fae88da5e442451).

**Comment by algernon** [comment]
That means I broke [one of these](https://github.com/keyboardio/Kaleidoscope/blob/aecc29a31341cd21f5d90133b5bcf9237eb981a5/src/kaleidoscope/plugin/Escape-OneShot.cpp#L31), which is entirely possible.

My suspicion is that I broke `isActive()`, but will have to debug it further. Since I can easily reproduce the problem, this shouldn't take too long.

**Comment by algernon** [comment]
Turns out that `isActive()` is fine, but `isPressed()` and `isSticky()` always return true.
