### ISSUE TITLE
OSX: Print dialog popping up during build sometimes

### ISSUE THREAD

**Issue by sboesebeck** [keyboardio/Kaleidoscope#835]
Sometimes during build the print dialog pops up, it seems to be related with hightlighting:
<img width="1641" alt="PrintDialog" src="https://user-images.githubusercontent.com/1639447/80474459-c50f0280-8947-11ea-9903-ef133a8e9636.png">

If you print the file, it is just a couple of log outputs:
[printDuringBuild.pdf](https://github.com/keyboardio/Kaleidoscope/files/4544857/printDuringBuild.pdf)

There are several of those, As is happens _during_ printing out some log line, it really seems to be related to highlighting.

Operating System: OSX Catalina
Shell: ZSH
Terminal: iTerm2

**Comment by obra** [comment]
That's pretty weird. Looks like iTerm is just a little nutty about this interaction with gcc error colorization. I'm going to close this bug, because it's not something we can really do anything about.

https://gitlab.com/gnachman/iterm2/-/issues/2027
https://sourceforge.net/p/iterm/discussion/230320/thread/a9be4ac6/
https://gitlab.com/gnachman/iterm2/-/issues/3702
https://superuser.com/questions/1268978/running-cat-on-a-file-opens-the-print-dialog
https://bugzilla.mozilla.org/show_bug.cgi?id=1319166
